# Generated by Django 4.2.13 on 2024-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0002_alter_caso_casestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='casCodigo',
            field=models.CharField(db_comment='Codigo unico del caso', max_length=20, unique=True),
        ),
    ]
