# Generated by Django 4.2.13 on 2024-06-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0003_alter_caso_cascodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoprocedimiento',
            name='tipDescripcion',
            field=models.TextField(db_comment='texto con la descripcion del tipo de procedimiento', default='Sin descripcion', max_length=1000),
        ),
    ]
